[package]
name = "youtube-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.20.0"
reqwest = "^0.11"
rocket = "0.5.0"
serde = "1.0.200"
serde_json = "1.0.116"
shuttle-rocket = "0.44.0"
shuttle-runtime = "0.44.0"
tokio = "1.37.0"
youtube-captions = "0.1.0"
